---
- name: Configure Ubuntu LTS release upgrader
  ansible.builtin.lineinfile:
    path: /etc/update-manager/release-upgrades
    regexp: ^Prompt=
    line: Prompt=lts
  tags:
  - uip_repos_landscape
  - uip_preupgrade
  - uip_discovery
  - uip_postcheck
  - uip_postupgrade
- name: Configure Landscape target APT source
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/uip-{{ uip_dst_name }}.list
    mode: '0644'
    content: 'deb {{ uip_repo_def.target_urls[0] }} {{ uip_repo_def.dst_series }} main restricted universe multiverse

      deb {{ uip_repo_def.target_urls[0] }} {{ uip_repo_def.dst_series }}-updates main restricted universe multiverse

      deb {{ uip_repo_def.target_urls[0] }} {{ uip_repo_def.dst_series }}-security main restricted universe multiverse

      '
  when: uip_repo_def.target_urls is defined
  tags:
  - uip_repos_landscape
  - uip_preupgrade
  - uip_discovery
  - uip_postcheck
  - uip_postupgrade
