---
- name: Set target repository URL
  ansible.builtin.set_fact:
    uip_repo_target_url: "{{\n  uip_repo_def.dst_url\n  | default(uip_repo_def.base_url ~ '/' ~ uip_repo_def.dst_repo)\n}}"
  tags:
    - uip_preupgrade
    - uip_repos_nexus
    - uip_discovery
    - uip_postcheck
    - uip_postupgrade
- name: Configure RPM target repository
  ansible.builtin.copy:
    dest: /etc/yum.repos.d/uip-{{ uip_dst_name }}.repo
    mode: '0644'
    content: '[uip-{{ uip_dst_name }}]

      name=UIP {{ uip_dst_name }}

      baseurl={{ uip_repo_target_url }}

      enabled=1

      gpgcheck={{ 1 if uip_repo_gpg else 0 }}

      gpgkey={{ uip_repo_def.gpg_key | default('''') }}

      '
  when: uip_pkg_mgr in ['yum', 'dnf']
  tags:
    - uip_preupgrade
    - uip_repos_nexus
    - uip_discovery
    - uip_postcheck
    - uip_postupgrade
- name: Configure APT target repository
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/uip-{{ uip_dst_name }}.list
    mode: '0644'
    content: 'deb {{ uip_repo_target_url }} {{ uip_repo_def.dst_suite }} {{ uip_repo_components }}

      '
  vars:
    uip_repo_components: '{{ uip_repo_def.components | default([''main'']) | join('' '') }}'
  when: uip_pkg_mgr == "apt"
  tags:
    - uip_preupgrade
    - uip_repos_nexus
    - uip_discovery
    - uip_postcheck
    - uip_postupgrade
- name: Configure Zypper target repository
  ansible.builtin.copy:
    dest: /etc/zypp/repos.d/uip-{{ uip_dst_name }}.repo
    mode: '0644'
    content: '[uip-{{ uip_dst_name }}]

      name=UIP {{ uip_dst_name }}

      enabled=1

      autorefresh=1

      baseurl={{ uip_repo_target_url }}

      type=rpm-md

      gpgcheck={{ 1 if uip_repo_gpg else 0 }}

      '
  when: uip_pkg_mgr == "zypper"
  tags:
    - uip_preupgrade
    - uip_repos_nexus
    - uip_discovery
    - uip_postcheck
    - uip_postupgrade


- name: Apply explicit repository binding intent
  ansible.builtin.debug:
    msg:
      - "repo_manager={{ uip_repo_mgr }}"
      - "source_activation_key={{ uip_repo_src_binding | default('') }}"
      - "target_activation_key={{ uip_repo_dst_binding | default('') }}"
      - "source_environment={{ uip_repo_src_environment | default('') }}"
      - "target_environment={{ uip_repo_dst_environment | default('') }}"
      - "source_content_view={{ uip_repo_src_cv | default('') }}"
      - "target_content_view={{ uip_repo_dst_cv | default('') }}"
  when:
    - (uip_repo_dst_binding | default('') | length > 0)
      or (uip_repo_dst_environment | default('') | length > 0)
      or (uip_repo_dst_cv | default('') | length > 0)
  tags:
    - uip_discovery
    - uip_preupgrade
    - uip_postcheck
    - uip_postupgrade
