---
- name: Refresh SUSE Manager repositories
  ansible.builtin.command: zypper --non-interactive refresh
  changed_when: false
  tags:
  - uip_repos_suse_mgr
  - uip_preupgrade
  - uip_suse
  - uip_discovery
  - uip_postcheck
  - uip_postupgrade
