---
- name: Include RHEL kernel remediation tasks
  ansible.builtin.import_tasks: kernel.yml
  tags:
    - uip_remediate
    - uip_remediate_rhel
    - uip_remediate_kernel
    - uip_preupgrade

- name: Include RHEL bootability verification tasks
  ansible.builtin.import_tasks: bootability.yml
  when: uip_bootloader_bootability_checks | bool
  tags:
    - uip_remediate
    - uip_remediate_rhel
    - uip_remediate_bootloader
    - uip_preupgrade

- name: Include RHEL GRUB remediation tasks
  ansible.builtin.import_tasks: grub.yml
  when: uip_remediate_grub_reconfigure | bool
  tags:
    - uip_remediate
    - uip_remediate_rhel
    - uip_remediate_grub
    - uip_preupgrade

- name: Include RHEL inhibitor remediation tasks
  ansible.builtin.import_tasks: inhibitors.yml
  when: uip_remediate_fix_inhibitors | bool
  tags:
    - uip_remediate
    - uip_remediate_rhel
    - uip_remediate_inhibitors
    - uip_preupgrade
