---
- name: Include common precheck tasks
  ansible.builtin.import_tasks: tasks.d/common.yml
  tags:
    - uip_precheck
    - uip_precheck_sys
    - uip_preupgrade

- name: Include RHEL precheck tasks
  ansible.builtin.import_tasks: tasks.d/rhel.yml
  when: uip_os == "rhel"
  tags:
    - uip_precheck
    - uip_precheck_rhel
    - uip_preupgrade

- name: Include Debian or Ubuntu precheck tasks
  ansible.builtin.import_tasks: tasks.d/debian.yml
  when: uip_os in ["debian", "ubuntu"]
  tags:
    - uip_precheck
    - uip_precheck_apt
    - uip_preupgrade

- name: Include SUSE precheck tasks
  ansible.builtin.import_tasks: tasks.d/suse.yml
  when: uip_os == "sles"
  tags:
    - uip_precheck
    - uip_precheck_suse
    - uip_preupgrade
