---
- name: Detect Debian GRUB command
  ansible.builtin.command: command -v update-grub
  register: uip_update_grub_cmd
  changed_when: false
  failed_when: false
  tags:
    - uip_remediate
    - uip_remediate_debian
    - uip_remediate_grub
    - uip_preupgrade

- name: Reconfigure Debian GRUB
  ansible.builtin.command: update-grub
  register: uip_debian_update_grub
  changed_when: true
  failed_when: uip_debian_update_grub.rc != 0
  when: uip_update_grub_cmd.rc == 0
  tags:
    - uip_remediate
    - uip_remediate_debian
    - uip_remediate_grub
    - uip_preupgrade
