---
- name: Check APT availability
  ansible.builtin.command: command -v apt-get
  register: uip_precheck_apt_cmd
  changed_when: false
  failed_when: uip_precheck_apt_cmd.rc != 0
  tags:
    - uip_precheck
    - uip_precheck_apt
    - uip_preupgrade

- name: Validate APT package database
  ansible.builtin.command: apt-get check
  register: uip_precheck_apt_check
  changed_when: false
  failed_when: false
  tags:
    - uip_precheck
    - uip_precheck_apt
    - uip_preupgrade
