---
- name: Run SUSE migration
  ansible.builtin.command: '{{ uip_upg_tool }}'
  register: uip_suse_upgrade
  changed_when: true
  tags:
    - uip_upgrade
    - uip_upgrade_suse
    - uip_postupgrade
    - uip_suse
