---
- name: Refresh SUSE repositories before migration
  ansible.builtin.command: zypper --non-interactive refresh
  register: uip_suse_refresh
  changed_when: false
  failed_when: false
  tags:
    - uip_remediate
    - uip_remediate_suse
    - uip_remediate_inhibitors
    - uip_preupgrade

- name: Rebuild SUSE initrd
  ansible.builtin.command: mkinitrd
  register: uip_suse_mkinitrd
  changed_when: true
  failed_when: uip_suse_mkinitrd.rc != 0
  when: uip_initramfs_rebuild | bool
  tags:
    - uip_remediate
    - uip_remediate_suse
    - uip_remediate_initramfs
    - uip_preupgrade
