---
- name: Mark lock as upgrade_started
  ansible.builtin.copy:
    dest: '{{ uip_lock_file }}'
    mode: '0640'
    content: 'id: "{{ inventory_hostname }}-{{ uip_path_key }}"

      host: "{{ inventory_hostname }}"

      distro: "{{ uip_os }}"

      src_ver: "{{ uip_src_ver }}"

      dst_ver: "{{ uip_dst_ver }}"

      path: "{{ uip_path_key }}"

      state: "upgrade_started"

      repo_mgr: "{{ uip_repo_mgr }}"

      updated_at: "{{ ansible_date_time.iso8601 }}"

      '
  tags:
    - uip_upgrade
    - uip_postupgrade
- name: Run OS upgrade command
  ansible.builtin.command: '{{ uip_upg_tool }}'
  register: uip_upgrade_run
  changed_when: true
  when: uip_mode == "enforce"
  tags:
    - uip_upgrade
    - uip_postupgrade
- name: Save upgrade output
  ansible.builtin.copy:
    dest: '{{ uip_report_dir }}/upgrade-output.txt'
    content: 'stdout:

      {{ uip_upgrade_run.stdout | default('''') }}

      stderr:

      {{ uip_upgrade_run.stderr | default('''') }}

      '
    mode: '0640'
  when: uip_mode == "enforce"
  tags:
    - uip_upgrade
    - uip_postupgrade
- name: Reboot after OS upgrade
  ansible.builtin.include_role:
    name: uip-reboot
  vars:
    uip_reboot_reason: os_upgrade
    uip_reboot_current_step: uip-upgrade
    uip_reboot_next_step: uip-postcheck
  when:
    - uip_allow_reboot | bool
    - uip_mode == "enforce"
  tags:
    - uip_upgrade
    - uip_postupgrade
