---
- name: Run Ubuntu do-release-upgrade
  ansible.builtin.command: do-release-upgrade -f DistUpgradeViewNonInteractive
  register: uip_ubuntu_upgrade
  changed_when: true
  tags:
    - uip_upgrade
    - uip_upgrade_ubuntu
    - uip_postupgrade
    - uip_ubuntu
