---
all:
  children:
    linux:
      hosts:
        srv01:
          ansible_host: 192.0.2.10
          uip_dst_ver: "20.04"
          # uip_repo_mgr can be omitted.
          # Auto-detection is enabled by default.
