---
- name: Run Leapp upgrade
  ansible.builtin.command: leapp upgrade
  register: uip_leapp_upgrade
  changed_when: true
  tags:
    - uip_upgrade
    - uip_upgrade_rhel
    - uip_postupgrade
    - uip_rhel
