---
- name: Run RHEL 6 to 7 upgrade tool
  ansible.builtin.command: "redhat-upgrade-tool --network 7 --cleanup-post"
  register: uip_upgrade_out
  async: 7200
  poll: 30
  when: uip_mode == 'enforce'
