---
- name: Snapshot placeholder
  ansible.builtin.debug:
    msg: Snapshot type={{ uip_snap_type }} enabled={{ uip_snap_enabled }}
  tags:
    - uip_snapshot
    - uip_preupgrade

- name: Run baseline update after snapshot completion
  ansible.builtin.include_role:
    name: uip-update
  when:
    - uip_update_before_upgrade | bool
  tags:
    - uip_snapshot
    - uip_preupgrade
