---
- name: Autoremove obsolete Ubuntu kernels and packages
  ansible.builtin.apt:
    autoremove: true
    purge: true
  when: uip_remediate_boot_cleanup | bool
  tags:
    - uip_remediate
    - uip_remediate_ubuntu
    - uip_remediate_kernel
    - uip_preupgrade
