---
- name: Include common precheck tasks
  ansible.builtin.import_tasks: tasks.d/common.yml
  tags:
    - uip_precheck
    - uip_precheck_sys
    - uip_preupgrade

- name: Include RHEL precheck tasks
  ansible.builtin.include_tasks: tasks.d/rhel/main.yml
  when: uip_os == "rhel"
  tags:
    - uip_precheck
    - uip_precheck_rhel
    - uip_preupgrade

- name: Include Debian or Ubuntu precheck tasks
  ansible.builtin.include_tasks: tasks.d/debian/main.yml
  when: uip_os in ["debian", "ubuntu"]
  tags:
    - uip_precheck
    - uip_precheck_apt
    - uip_preupgrade

- name: Include SUSE precheck tasks
  ansible.builtin.include_tasks: tasks.d/suse/main.yml
  when: uip_os == "sles"
  tags:
    - uip_precheck
    - uip_precheck_suse
    - uip_preupgrade

- name: Include service dependency graph tasks
  ansible.builtin.import_tasks: tasks.d/dependency_graph.yml
  tags:
    - uip_precheck
    - uip_preupgrade

- name: Call uipAgents for application contract baseline
  ansible.builtin.include_role:
    name: uipAgents
  vars:
    uip_agents_phase: baseline
  tags:
    - uip_precheck
    - uip_preupgrade

- name: Include operational governance tasks
  ansible.builtin.import_tasks: tasks.d/operational.yml
  tags:
    - uip_precheck
    - uip_preupgrade
