---
- name: Check zypper availability
  ansible.builtin.command: command -v zypper
  register: uip_precheck_zypper_cmd
  changed_when: false
  failed_when: uip_precheck_zypper_cmd.rc != 0
  tags:
    - uip_precheck
    - uip_precheck_suse
    - uip_preupgrade

- name: Validate zypper repositories
  ansible.builtin.command: zypper --non-interactive repos
  register: uip_precheck_zypper_repos
  changed_when: false
  failed_when: false
  tags:
    - uip_precheck
    - uip_precheck_suse
    - uip_preupgrade
