---
- name: Rollback Linux in-place upgrade
  hosts: linux
  become: true
  gather_facts: true
  roles:
    - role: uipCommon
      tags:
        - always
        - uip_common
        - uip_rollback
    - role: uipRollback
      tags:
        - uip_rollback
    - role: uipReport
      tags:
        - always
        - uip_report
        - uip_rollback
