---
- name: Enterprise Linux in-place upgrade
  hosts: linux
  become: true
  gather_facts: true
  serial: '{{ uip_serial }}'
  roles:
    - role: uipCommon
      tags:
        - always
        - uip_common
        - uip_preupgrade
    - role: uipDiscovery
      tags:
        - uip_discovery
        - uip_preupgrade
    - role: uipSnapshot
      tags:
        - uip_snapshot
        - uip_preupgrade
    - role: uipPrecheck
      tags:
        - uip_precheck
        - uip_preupgrade
    - role: uipRemediate
      tags:
        - uip_remediate
        - uip_preupgrade
    - role: uipUpgrade
      tags:
        - uip_upgrade
        - uip_postupgrade
    - role: uipPostcheck
      tags:
        - uip_postcheck
        - uip_postupgrade
    - role: uipReport
      tags:
        - always
        - uip_report
        - uip_postupgrade
