---
uip_mode: enforce
uip_resume: false
uip_serial: 1
uip_lock_dir: /var/lib/uip
uip_lock_file: /var/lib/uip/upgrade.lock
uip_done_file: /var/lib/uip/upgrade.done
uip_state_file: /var/lib/uip/state.yml
uip_log_dir: /var/log/uip
uip_report_dir: /var/log/uip/reports
uip_allow_skip: false
uip_allow_reboot: true
uip_repo_mgr: auto
uip_repo_detect: true
uip_repo_validate: true
uip_repo_gpg: true
uip_repo_freeze: true
uip_repo_enforce_target: true
uip_snap_enabled: true
uip_snap_type: none
uip_snap_ttl_h: 72
uip_pre_min_root_mb: 8192
uip_pre_min_boot_mb: 512
uip_pre_min_var_mb: 6144
uip_pre_min_tmp_mb: 4096
uip_svc_crit:
  - sshd
uip_ports_crit:
  - 22
uip_health_cmds:
  - systemctl is-system-running || true
  - systemctl --failed || true
uip_update_before_upgrade: true
uip_update_autoremove: false
uip_update_clean_cache: true
uip_reboot_timeout: 2700
uip_reboot_connect_timeout: 30
uip_reboot_pre_delay: 5
uip_reboot_post_delay: 20
uip_reboot_state_file: /var/lib/uip/reboot-state.yml
uip_reboot_current_step: unknown
uip_reboot_next_step: unknown
uip_remediate_fs_size_threshold_mb: 2048
uip_remediate_fstab_backup: "/etc/before-uip.fstab.original"
uip_remediate_fstab_network_prefix: "##-UIP-##"
uip_remediate_kernel_keep: 2
uip_remediate_boot_cleanup: true
uip_remediate_lvm_extend: true
uip_remediate_grub_reconfigure: true
uip_remediate_fix_inhibitors: true
uip_remediate_comment_network_mounts: true

uip_rhel6_to_7_instrepo: ""

uip_pre_dns_targets: []

uip_pre_repo_health_urls: []

uip_pre_min_boot_inode_pct_free: 5

uip_pre_min_var_lib_leapp_mb: 4096

uip_disable_agents: true

uip_disable_patch_automation: true

uip_app_pre_snapshot_cmds: []

uip_app_post_validation_cmds: []

uip_initramfs_rebuild: true

uip_validate_grubby: true

uip_selinux_relabel_onboot: false

uip_report_final_file: "{{ uip_report_dir }}/uip-final-report.yml"

uip_agent_services:
  - falcon-sensor
  - sentinelone
  - sentineld
  - taniumclient
  - qualys-cloud-agent
  - ds_agent
  - cbdaemon
  - puppet
  - chef-client
  - salt-minion

uip_patch_automation_services:
  - unattended-upgrades
  - apt-daily.timer
  - apt-daily-upgrade.timer
  - dnf-automatic.timer
  - yum-cron
  - packagekit
