---
- ansible.builtin.import_tasks: tasks.d/common.yml
  tags:
    - uip_repos
    - uip_repos_common

- ansible.builtin.import_tasks: tasks.d/satellite.yml
    - uip_preupgrade
  when: uip_repo_mgr == "satellite"
  tags:
    - uip_repos
    - uip_repos_satellite

- ansible.builtin.import_tasks: tasks.d/artifactory.yml
  when: uip_repo_mgr == "artifactory"
  tags:
    - uip_repos
    - uip_repos_artifactory

- ansible.builtin.import_tasks: tasks.d/nexus.yml
  when: uip_repo_mgr == "nexus"
  tags:
    - uip_repos
    - uip_repos_nexus

- ansible.builtin.import_tasks: tasks.d/pulp.yml
  when: uip_repo_mgr == "pulp"
  tags:
    - uip_repos
    - uip_repos_pulp

- ansible.builtin.import_tasks: tasks.d/landscape.yml
  when: uip_repo_mgr == "landscape"
  tags:
    - uip_repos
    - uip_repos_landscape

- ansible.builtin.import_tasks: tasks.d/suse_mgr.yml
  when: uip_repo_mgr == "suse_mgr"
  tags:
    - uip_repos
    - uip_repos_suse_mgr

- ansible.builtin.import_tasks: tasks.d/uyuni.yml
  when: uip_repo_mgr == "uyuni"
  tags:
    - uip_repos
    - uip_repos_uyuni

- ansible.builtin.import_tasks: tasks.d/airgap.yml
  when: uip_repo_mgr == "airgap"
  tags:
    - uip_repos
    - uip_repos_airgap

- ansible.builtin.import_tasks: tasks.d/native.yml
  when: uip_repo_mgr == "native"
  tags:
    - uip_repos
    - uip_repos_native

- ansible.builtin.import_tasks: tasks.d/enforce_target.yml
  when: uip_repo_enforce_target | bool
  tags:
    - uip_repos
    - uip_repos_enforce_target
